server:
  port: 80

spring:
  application:
    name: tim-crowd-zuul
  redis:
    host: 127.0.0.1
  session:
    store-type: redis


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  routes:
    crowd-portal:
      service-id: tim-crowd-auth
      path: /**
    crowd-project:
      service-id: tim-crowd-project
      path: /project/**
    crowd-order:
      service-id: tim-crowd-order
      path: /order/**
    crowd-pay:
      service-id: tim-crowd-pay
      path: /pay/**
    ignored-services: "*"
    sensitive-headers: "*"
  ribbon.eager-load.enabled: true

ribbon:
  ReadTimeout: 200000
  ConnectTimeout: 200000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000000