server:
  port: 80

spring:
  application:
    name: tim-crowd-zuul
  redis:
    host: 127.0.0.1
  session:
    store-type: redis


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  routes:
    crowd-portal:
      service-id: tim-crowd-auth
      path: /**
    ignored-services: "*"
    sensitive-headers: "*"
  host:
    socket-timeout-millis: 200000
    connect-timeout-millis: 200000