server:
  port: 5000
spring:
  application:
    name: tim-crowd-project
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    accessKeyId: ************************
    accessKeySecret: ******************************
    bucketDomain: http://crowdfunding.oss-cn-hangzhou.aliyuncs.com
    bucketName: crowdfunding
    endPoint: http://oss-cn-hangzhou.aliyuncs.com