server:
  port: 4000
spring:
  application:
    name: tim-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
feign:
  client:
    config:
      default:
        ConnectTimeOut: 5000
        ReadTimeOut: 10000
